# Build stage
FROM node:20 AS builder

WORKDIR /kingsley_ogueri_ui_garden

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build-storybook

# Step 2: Serve Storybook static files with Nginx
FROM nginx:alpine

COPY --from=builder /kingsley_ogueri_ui_garden/storybook-static /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]  